# Generated by Django 5.1.1 on 2024-09-19 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appportfolio', '0002_personal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personal',
            options={'ordering': ['nombre'], 'verbose_name': 'Personal', 'verbose_name_plural': 'Personales'},
        ),
        migrations.RenameField(
            model_name='personal',
            old_name='Apellido2',
            new_name='apellido2',
        ),
        migrations.AddField(
            model_name='personal',
            name='edad',
            field=models.IntegerField(blank=True, null=True, verbose_name='Edad'),
        ),
        migrations.AlterField(
            model_name='habilidad',
            name='nivel',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nivel'),
        ),
    ]
